### ISSUE TITLE
PG needs to be built with libxml to use XML functions.

### ISSUE THREAD

**Issue by deathwish** [CircleCI-Public/cimg-postgres#18]
I recommend using the official builds from apt.postgresql.org, rather than attempting to get builds correct.
```
PG::FeatureNotSupported: ERROR:  unsupported XML feature
DETAIL:  This functionality requires the server to be built with libxml support.
HINT:  You need to rebuild PostgreSQL using --with-libxml.
```

**Comment by felicianotech** [comment]
We can't use the provided Apt repository as there's certain limitations it causes. Otherwise, that would be SO much easier for sure.

I'm not sure which image tag you're using but `cimg/postgres:13.4` and `cimg/postgres:9.6.23` have been updated with all of the config options that the official Debian package uses, including `libxml` support. Do you mind verifying that your issue is resolved if you can use one of those two images?

**Comment by felicianotech** [comment]
Following up, the image is built with libxml support: https://github.com/CircleCI-Public/cimg-postgres/blob/main/Dockerfile.template#L62

There's been no further response. Closing.
